@isTest
public class TestLavorazioneAttachment{
    
    public static testmethod void TestSetAttachmentProcessable(){
        
        /*LavorazioneAttachment instanza = new LavorazioneAttachment();
        
        Test.StartTest();
        // crea un contratto
        Contratto__c mioCont = new Contratto__c();
        mioCont.Note__c = 'testContratto';
        mioCont.Data_Inizio__c = System.Today();
        mioCont.Partita_IVA__c = 'll';
        mioCont.Titolo__c = 'ññññ';
        mioCont.Comune__c = 'Milano';
        insert mioCont;
        
        // crea l'attachment
        Attachment attach = new Attachment();
        attach.name = 'NomeAttach';
        Blob bodyAttach = Blob.valueOf('Questo é il body del attachment Test!');
        attach.Body = bodyAttach;
        attach.parentId = mioCont.id;
        insert attach;
        
        // chiama il metodo che rende il body processabile e la sbianca
        instanza.setAttachmentProcessable(attach.id, attach.parentId);
                
        System.Debug('Il contenuto del file in Log__c: \n ' + LavorazioneAttachment.logCorrispAttach[0].Integration_Json_file_data__c);
        Test.StopTest();*/
    }
}